version: '3'
services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    # volumes:
    #   - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
